// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace ProjectGame.HotFix.Resolvers.Resolvers
{
    public class GeneratedResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new GeneratedResolver();

        private GeneratedResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class GeneratedResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> lookup;

        static GeneratedResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(12)
            {
                { typeof(global::Config_Effect), 0 },
                { typeof(global::Config_EffectRoll), 1 },
                { typeof(global::Config_Item), 2 },
                { typeof(global::Config_Lobby_Items), 3 },
                { typeof(global::Config_Lobby_Skins), 4 },
                { typeof(global::Config_Lobby_Weapons), 5 },
                { typeof(global::Config_LocalObjectPool), 6 },
                { typeof(global::Config_LocalVFXPool), 7 },
                { typeof(global::Config_Modifier), 8 },
                { typeof(global::Config_RoomTemplate), 9 },
                { typeof(global::Config_SyncObjectPool), 10 },
                { typeof(global::Config_Weapon), 11 },
            };
        }

        internal static object GetFormatter(global::System.Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new ProjectGame.HotFix.Resolvers.Formatters.Config_EffectFormatter();
                case 1: return new ProjectGame.HotFix.Resolvers.Formatters.Config_EffectRollFormatter();
                case 2: return new ProjectGame.HotFix.Resolvers.Formatters.Config_ItemFormatter();
                case 3: return new ProjectGame.HotFix.Resolvers.Formatters.Config_Lobby_ItemsFormatter();
                case 4: return new ProjectGame.HotFix.Resolvers.Formatters.Config_Lobby_SkinsFormatter();
                case 5: return new ProjectGame.HotFix.Resolvers.Formatters.Config_Lobby_WeaponsFormatter();
                case 6: return new ProjectGame.HotFix.Resolvers.Formatters.Config_LocalObjectPoolFormatter();
                case 7: return new ProjectGame.HotFix.Resolvers.Formatters.Config_LocalVFXPoolFormatter();
                case 8: return new ProjectGame.HotFix.Resolvers.Formatters.Config_ModifierFormatter();
                case 9: return new ProjectGame.HotFix.Resolvers.Formatters.Config_RoomTemplateFormatter();
                case 10: return new ProjectGame.HotFix.Resolvers.Formatters.Config_SyncObjectPoolFormatter();
                case 11: return new ProjectGame.HotFix.Resolvers.Formatters.Config_WeaponFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1649 // File name should match first type name




// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace ProjectGame.HotFix.Resolvers.Formatters
{
    public sealed class Config_EffectFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Config_Effect>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Config_Effect value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(12);
            writer.Write(value.EffectID);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.CodeName, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<int[]>(formatterResolver).Serialize(ref writer, value.ModifierIDs, options);
            writer.Write(value.Repeatable);
            writer.Write(value.MaxLevel);
            writer.Write(value.EffectType);
            writer.Write(value.RollPool);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<int[]>(formatterResolver).Serialize(ref writer, value.SchoolIDs, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<int[]>(formatterResolver).Serialize(ref writer, value.ConflictSchoolIDs, options);
            writer.Write(value.BaseWeight);
            writer.Write(value.SchoolWeightBonus);
            writer.Write(value.Enabled);
        }

        public global::Config_Effect Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Config_Effect();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.EffectID = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.CodeName = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.ModifierIDs = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<int[]>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.Repeatable = reader.ReadBoolean();
                        break;
                    case 4:
                        ____result.MaxLevel = reader.ReadInt32();
                        break;
                    case 5:
                        ____result.EffectType = reader.ReadInt32();
                        break;
                    case 6:
                        ____result.RollPool = reader.ReadInt32();
                        break;
                    case 7:
                        ____result.SchoolIDs = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<int[]>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 8:
                        ____result.ConflictSchoolIDs = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<int[]>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 9:
                        ____result.BaseWeight = reader.ReadSingle();
                        break;
                    case 10:
                        ____result.SchoolWeightBonus = reader.ReadSingle();
                        break;
                    case 11:
                        ____result.Enabled = reader.ReadBoolean();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class Config_EffectRollFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Config_EffectRoll>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Config_EffectRoll value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(6);
            writer.Write(value.EffectID);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.DisplayName, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Description, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.UpgradeDescription, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.IconAddress, options);
            writer.Write(value.Enabled);
        }

        public global::Config_EffectRoll Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Config_EffectRoll();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.EffectID = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.DisplayName = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.Description = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.UpgradeDescription = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        ____result.IconAddress = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 5:
                        ____result.Enabled = reader.ReadBoolean();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class Config_ItemFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Config_Item>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Config_Item value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(5);
            writer.Write(value.ItemID);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Name, options);
            writer.Write(value.MaxStackSize);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.IconPath, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Description, options);
        }

        public global::Config_Item Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Config_Item();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.ItemID = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.Name = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.MaxStackSize = reader.ReadInt32();
                        break;
                    case 3:
                        ____result.IconPath = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        ____result.Description = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class Config_Lobby_ItemsFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Config_Lobby_Items>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Config_Lobby_Items value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(6);
            writer.Write(value.ItemID);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Name, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.ModleName, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.IconName, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Description, options);
            writer.Write(value.ItemSpawnSlot);
        }

        public global::Config_Lobby_Items Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Config_Lobby_Items();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.ItemID = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.Name = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.ModleName = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.IconName = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        ____result.Description = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 5:
                        ____result.ItemSpawnSlot = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class Config_Lobby_SkinsFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Config_Lobby_Skins>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Config_Lobby_Skins value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(5);
            writer.Write(value.SkinID);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Name, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.ModleName, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.IconName, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Description, options);
        }

        public global::Config_Lobby_Skins Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Config_Lobby_Skins();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.SkinID = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.Name = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.ModleName = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.IconName = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        ____result.Description = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class Config_Lobby_WeaponsFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Config_Lobby_Weapons>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Config_Lobby_Weapons value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(7);
            writer.Write(value.WeaponID);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Name, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.ModleName, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.IconName, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Description, options);
            writer.Write(value.WeaponSpawnSlot);
            writer.Write(value.WeaponEquipAnim);
        }

        public global::Config_Lobby_Weapons Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Config_Lobby_Weapons();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.WeaponID = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.Name = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.ModleName = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.IconName = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        ____result.Description = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 5:
                        ____result.WeaponSpawnSlot = reader.ReadInt32();
                        break;
                    case 6:
                        ____result.WeaponEquipAnim = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class Config_LocalObjectPoolFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Config_LocalObjectPool>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Config_LocalObjectPool value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(6);
            writer.Write(value.ConfigId);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.PoolId, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.GroupName, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.PrefabAddress, options);
            writer.Write(value.InitialCapacity);
            writer.Write(value.MaxSize);
        }

        public global::Config_LocalObjectPool Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Config_LocalObjectPool();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.ConfigId = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.PoolId = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.GroupName = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.PrefabAddress = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        ____result.InitialCapacity = reader.ReadInt32();
                        break;
                    case 5:
                        ____result.MaxSize = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class Config_LocalVFXPoolFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Config_LocalVFXPool>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Config_LocalVFXPool value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(6);
            writer.Write(value.ConfigId);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.PoolId, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.GroupName, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.PrefabAddress, options);
            writer.Write(value.InitialCapacity);
            writer.Write(value.MaxSize);
        }

        public global::Config_LocalVFXPool Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Config_LocalVFXPool();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.ConfigId = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.PoolId = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.GroupName = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.PrefabAddress = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        ____result.InitialCapacity = reader.ReadInt32();
                        break;
                    case 5:
                        ____result.MaxSize = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class Config_ModifierFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Config_Modifier>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Config_Modifier value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(6);
            writer.Write(value.ModifierID);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.CodeName, options);
            writer.Write(value.StatType);
            writer.Write(value.Operation);
            writer.Write(value.BaseValue);
            writer.Write(value.Enabled);
        }

        public global::Config_Modifier Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Config_Modifier();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.ModifierID = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.CodeName = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.StatType = reader.ReadInt32();
                        break;
                    case 3:
                        ____result.Operation = reader.ReadInt32();
                        break;
                    case 4:
                        ____result.BaseValue = reader.ReadSingle();
                        break;
                    case 5:
                        ____result.Enabled = reader.ReadBoolean();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class Config_RoomTemplateFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Config_RoomTemplate>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Config_RoomTemplate value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(9);
            writer.Write(value.TemplateId);
            writer.Write(value.RoomType);
            writer.Write(value.AllowedStrategyMask);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.PoolId, options);
            writer.Write(value.SupportedConnectorMask);
            writer.Write(value.AllowUnusedConnectors);
            writer.Write(value.AllowedRotations);
            writer.Write(value.Priority);
            writer.Write(value.Weight);
        }

        public global::Config_RoomTemplate Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Config_RoomTemplate();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.TemplateId = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.RoomType = reader.ReadInt32();
                        break;
                    case 2:
                        ____result.AllowedStrategyMask = reader.ReadInt32();
                        break;
                    case 3:
                        ____result.PoolId = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        ____result.SupportedConnectorMask = reader.ReadInt32();
                        break;
                    case 5:
                        ____result.AllowUnusedConnectors = reader.ReadBoolean();
                        break;
                    case 6:
                        ____result.AllowedRotations = reader.ReadInt32();
                        break;
                    case 7:
                        ____result.Priority = reader.ReadInt32();
                        break;
                    case 8:
                        ____result.Weight = reader.ReadSingle();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class Config_SyncObjectPoolFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Config_SyncObjectPool>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Config_SyncObjectPool value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(6);
            writer.Write(value.ConfigId);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.PoolId, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.GroupName, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.PrefabAddress, options);
            writer.Write(value.InitialCapacity);
            writer.Write(value.MaxSize);
        }

        public global::Config_SyncObjectPool Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Config_SyncObjectPool();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.ConfigId = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.PoolId = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.GroupName = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.PrefabAddress = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        ____result.InitialCapacity = reader.ReadInt32();
                        break;
                    case 5:
                        ____result.MaxSize = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class Config_WeaponFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Config_Weapon>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Config_Weapon value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(23);
            writer.Write(value.WeaponID);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Name, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.ModleName, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.IconName, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Description, options);
            writer.Write(value.WeaponSpawnSlot);
            writer.Write(value.WeaponEquipAnim);
            writer.Write(value.Enabled);
            writer.Write(value.Damage);
            writer.Write(value.FireRate);
            writer.Write(value.ReloadTime);
            writer.Write(value.MagSize);
            writer.Write(value.ReserveAmmo);
            writer.Write(value.AutoReload);
            writer.Write(value.CritChance);
            writer.Write(value.CritMultiplier);
            writer.Write(value.ProjectileSpeed);
            writer.Write(value.ProjectileCount);
            writer.Write(value.SpreadAngle);
            writer.Write(value.BounceCount);
            writer.Write(value.PierceCount);
            writer.Write(value.ProjectileSize);
            writer.Write(value.ProjectileLifeTime);
        }

        public global::Config_Weapon Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Config_Weapon();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.WeaponID = reader.ReadInt32();
                        break;
                    case 1:
                        ____result.Name = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.ModleName = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.IconName = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        ____result.Description = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 5:
                        ____result.WeaponSpawnSlot = reader.ReadInt32();
                        break;
                    case 6:
                        ____result.WeaponEquipAnim = reader.ReadInt32();
                        break;
                    case 7:
                        ____result.Enabled = reader.ReadBoolean();
                        break;
                    case 8:
                        ____result.Damage = reader.ReadSingle();
                        break;
                    case 9:
                        ____result.FireRate = reader.ReadSingle();
                        break;
                    case 10:
                        ____result.ReloadTime = reader.ReadSingle();
                        break;
                    case 11:
                        ____result.MagSize = reader.ReadInt32();
                        break;
                    case 12:
                        ____result.ReserveAmmo = reader.ReadInt32();
                        break;
                    case 13:
                        ____result.AutoReload = reader.ReadBoolean();
                        break;
                    case 14:
                        ____result.CritChance = reader.ReadSingle();
                        break;
                    case 15:
                        ____result.CritMultiplier = reader.ReadSingle();
                        break;
                    case 16:
                        ____result.ProjectileSpeed = reader.ReadSingle();
                        break;
                    case 17:
                        ____result.ProjectileCount = reader.ReadInt32();
                        break;
                    case 18:
                        ____result.SpreadAngle = reader.ReadSingle();
                        break;
                    case 19:
                        ____result.BounceCount = reader.ReadInt32();
                        break;
                    case 20:
                        ____result.PierceCount = reader.ReadInt32();
                        break;
                    case 21:
                        ____result.ProjectileSize = reader.ReadSingle();
                        break;
                    case 22:
                        ____result.ProjectileLifeTime = reader.ReadSingle();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name

